exports.constants = {
  //apiUrl
  apiUrl: "http://localhost:3001/api",
  //action type
  LOGIN_SUCCESS: "LOGIN_SUCCESS",
  LOGIN_FAILURE: "LOGIN_FAILURE",
  LOGOUT: "LOGOUT",
  REGISTER_SUCCESS: "REGISTER_SUCCESS",
  REGISTER_FAILURE: "REGISTER_FAILURE",
  //popup
  POPUP_LOGIN: "POPUP_LOGIN",
  HIDE_POPUP: "HIDE_POPUP",
  SHOW_LOADING_STATUS: "SHOW_LOADING_STATUS",
  CLEAR_AUTH_MESSAGE: "CLEAR_MESSAGE",
  POPUP_FORGOTPASS: "POPUP_FORGOTPASS",
  //reducer status
  LOADING: "LOADING",
  SUCCESS: "SUCCESS",
  FAILURE: "FAILURE",
  //dentist
  GET_DENTISTS_SUCCESS: "GET_DENTISTS_SUCCESS",
  GET_DENTISTS_FAILURE: "GET_DENTISTS_FAILURE",
  GET_DENTIST_SUCCESS: "GET_DENTIST_SUCCESS",
  GET_DENTIST_FAILURE: "GET_DENTIST_FAILURE",
  CREATE_DENTIST_SUCCESS: "CREATE_DENTIST_SUCCESS",
  CREATE_DENTIST_FAILURE: "CREATE_DENTIST_FAILURE",
  DELETE_DENTIST_SUCCESS: "DELETE_DENTIST_SUCCESS",
  DELETE_DENTIST_FAILURE: "DELETE_DENTIST_FAILURE",
  UPDATE_DENTIST_SUCCESS: "UPDATE_DENTIST_SUCCESS",
  UPDATE_DENTIST_FAILURE: "UPDATE_DENTIST_FAILURE",
  //service
  GET_SERVICE_SUCCESS: "GET_SERVICE_SUCCESS",
  GET_SERVICE_FAILURE: "GET_SERVICE_FAILURE",
  GET_SCHEDULE_SUCCESS: "GET_SCHEDULE_SUCCESS",
  GET_SCHEDULE_FAILURE: "GET_SCHEDULE_FAILURE",
  //appointment
  MAKE_APPOINTMENT_SUCCESS: "MAKE_APPOINTMENT_SUCCESS",
  MAKE_APPOINTMENT_FAILURE: "MAKE_APPOINTMENT_FAILURE",
  GET_APPOINTMENTS_SUCCESS: "GET_APPOINTMENTS_SUCCESS",
  GET_APPOINTMENTS_FAILURE: "GET_APPOINTMENTS_FAILURE",
  CANCEL_APPOINTMENT_SUCCESS: "CANCEL_APPOINTMENT_SUCCESS",
  CANCEL_APPOINTMENT_FAILURE: "CANCEL_APPOINTMENT_FAILURE",
  //schedule
  ADD_SCHEDULE_SUCCESS: "ADD_SCHEDULE_SUCCESS",
  ADD_SCHEDULE_FAILURE: "ADD_SCHEDULE_FAILURE",
  UPDATE_SCHEDULE_SUCCESS: "UPDATE_SCHEDULE_SUCCESS",
  UPDATE_SCHEDULE_FAILURE: "UPDATE_SCHEDULE_FAILURE",
  //page
  GET_HOME_SUCCESS: "GET_HOME_SUCCESS",
  GET_HOME_FAILURE: "GET_HOME_FAILURE",
  GET_ADMIN_SUCCESS: "GET_ADMIN_SUCCESS",
  GET_ADMIN_FAILURE: "GET_ADMIN_FAILURE",
};
