exports.constants = {
  //apiUrl
  apiUrl: "http://localhost:3001/api",
  //action type
  LOGIN_SUCCESS: "LOGIN_SUCCESS",
  LOGIN_FAILURE: "LOGIN_FAILURE",
  LOGOUT: "LOGOUT",
  REGISTER_SUCCESS: "REGISTER_SUCCESS",
  REGISTER_FAILURE: "REGISTER_FAILURE",
  POPUP_LOGIN: "POPUP_LOGIN",
  HIDE_POPUP: "HIDE_POPUP",
  POPUP_FORGOTPASS: "POPUP_FORGOTPASS",
};
